feat: grpc backend
ZupIT/beagle-grpc pull request #8
Opened 2021-06-07 20:23 UTC by luismaximozup

2021-06-07 20:37 UTC, ze12augusto requested changes

2021-06-07 20:37 UTC, ze12augusto commented on backend/.idea/.name
> +Beagle Helpers Backend Examples and Libs
Remove .idea folder from project and put it on gitignore, if need just keep an specific file and ignore the others

2021-06-07 20:39 UTC, uziasferreirazup requested changes

2021-06-07 20:39 UTC, uziasferreirazup commented on gradlew
> +#!/usr/bin/env sh
please remove gradle from root of project.

2021-06-07 20:40 UTC, uziasferreirazup commented on gradlew
> +#!/usr/bin/env sh
you don't need to add the Gradle in the root of the project to run the workflow, access the directory, and run the Gradle referent of the project.

2021-06-07 20:43 UTC, uziasferreirazup requested changes

2021-06-07 20:43 UTC, uziasferreirazup commented on .gitignore
> +*.orig
I think all these lines can be put in git ignore of project backend.

2021-06-07 20:44 UTC, uziasferreirazup commented
I realized that for each module you have its own gradle, what do you think of changing this strategy to have the backend folder and all the modules inside and one connected to the other, after all if you change something you will want to run the samples and everything in a single place would be better like the Beagle

2021-06-07 20:51 UTC, luismaximozup commented on backend/.idea/.name
> +Beagle Helpers Backend Examples and Libs
ok

2021-06-07 20:52 UTC, luismaximozup commented on gradlew
> +#!/usr/bin/env sh
done

2021-06-07 20:53 UTC, luismaximozup commented on .gitignore
> +*.orig
but this also works for android, it would avoid replicating two identical gitignores in different projects. Both use kotlin, so it's possible to reuse, don't you agree?

2021-06-07 20:55 UTC, uziasferreirazup commented on .gitignore
> +*.orig
this will only make git ignore longer and confusing, the beagle is living proof of that haha

2021-06-08 14:03 UTC, uziasferreirazup commented on backend/build.gradle
> +        classpath "com.vanniktech:gradle-maven-publish-plugin:0.13.0"
what do you think about using the latest version of maven publish?

2021-06-08 14:03 UTC, uziasferreirazup commented on backend/build.gradle
> +    ext.beagle_grpc_version = "0.0.1"
shouldn't the first generated version be 1.0.0?

2021-06-08 14:27 UTC, luismaximozup commented on backend/build.gradle
> +    id "com.github.ben-manes.versions" version "0.33.0"
yes - https://github.com/ben-manes/gradle-versions-plugin

2021-06-08 14:27 UTC, luismaximozup commented on backend/build.gradle
> +    id "com.github.ben-manes.versions" version "0.33.0"
ok

2021-06-08 14:28 UTC, luismaximozup commented on backend/build.gradle
> +        classpath "org.jetbrains.dokka:dokka-gradle-plugin:1.4.20"
yes, ben-manes plugin use it.

2021-06-08 14:28 UTC, luismaximozup commented on backend/build.gradle
> +    ext.beagle_grpc_version = "0.0.1"
ok

2021-06-08 14:28 UTC, luismaximozup commented on backend/build.gradle
> +        classpath "com.vanniktech:gradle-maven-publish-plugin:0.13.0"
ok

2021-06-08 14:28 UTC, luismaximozup commented on backend/build.gradle
> +    ext.beagle_version = "1.7.0"
ok

2021-06-08 17:26 UTC, ze12augusto approved these changes

2021-06-08 17:41 UTC, uziasferreirazup commented on backend/grpc-backend-lib/README.md
> +    implementation("br.com.zup:grpc-backend:0.0.1")
```suggestion
    implementation("br.com.zup.beagle:grpc-backend:0.0.1")
```

2021-06-08 17:41 UTC, uziasferreirazup commented on backend/grpc-backend-lib/README.md
> +            <groupId>br.com.zup</groupId>
```suggestion
            <groupId>br.com.zup.beagle</groupId>
```

2021-06-08 17:41 UTC, uziasferreirazup commented on backend/grpc-backend-lib/src/main/kotlin/br/com/zup/beagle/BeagleGrpcUtil.kt
> +package br.com.zup.grpc
```suggestion
package br.com.zup.beagle.grpc
```

2021-06-08 17:41 UTC, uziasferreirazup commented on backend/grpc-backend-lib/src/main/kotlin/br/com/zup/beagle/BeagleScreenService.kt
> +package br.com.zup.grpc
```suggestion
package br.com.zup.beagle.grpc
```

2021-06-08 17:41 UTC, uziasferreirazup commented on backend/grpc-backend-lib/src/main/kotlin/br/com/zup/beagle/exception/BeagleException.kt
> +package br.com.zup.grpc.exception
```suggestion
package br.com.zup.beagle.grpc.exception
```

2021-06-08 17:41 UTC, uziasferreirazup commented on backend/grpc-backend-lib/src/test/kotlin/br.com.zup.grpc/BeagleGrpcUtilTest.kt
> +package br.com.zup.grpc
```suggestion
package br.com.zup.beagle.grpc
```

2021-06-08 17:41 UTC, uziasferreirazup commented on backend/grpc-backend-lib/src/test/kotlin/br.com.zup.grpc/BeagleScreenServiceTest.kt
> +package br.com.zup.grpc
```suggestion
package br.com.zup.beagle.grpc
```

2021-06-08 20:59 UTC, luismaximozup commented on .gitignore
> +*.orig
I don't think this is a problem, as long as everything is well organized and separated by comments for example, it's easy to maintain.

2021-06-09 13:53 UTC, igorgiumellizup approved these changes

2021-06-09 13:58 UTC, uziasferreirazup approved these changes

2021-06-09 13:59 UTC, merged